# Numpy in Python
***

## Introduction

__NumPy__ is a basic package for scientific computing. It is a Python language implementation which includes:
- The powerful N-dimensional array structure
- Sophisticated functions
- Tools that can be integrated into C/C++ and Fortran code
- Linear algebra, Fourier transform and random number features

In addition to being used for scientific computing, NumPy also can be used as an efficient multi-dimensional container for general data. Because it can work with any type of data, NumPy can be integrated into multiple types of databases seamlessly and efficiently.

***

## Basics

In [1]:
# linear algebra
import numpy as np 

### Basic Porperties and array creation

Here is an array with rank 1, and the length of the axis is 3:

In [2]:
[1,2,3]

[1, 2, 3]

Below is an array with rank 2, and the length of the axis is 3 too:

In [3]:
[[ 1, 2, 3],[ 4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

We can create an array of NumPy through the array function, for example:

In [4]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print("a: ",a)
print("b: ",b)

a:  [1 2 3]
b:  [[1 2 3]
 [4 5 6]]


Note that the square brackets are required here. And the following way of writing is wrong:

<br>
NumPy's array class is ndarray, which has an alias numpy.array, but it's different from array.array in the Python standard library. The latter is just a one-dimensional array. The features of ndarray are as follows: 

***

## ndarray

- __ndarray.ndim__: the dimension number of the array. It's called rank in Python.
- __ndarray.shape__: the dimension of the array. It's a series of numbers whose length is determined by the dimension （ndim） of the array. For example, the shape of a one-dimensional array with length n is n. And the shape of an array with n rows and m columns is n,m.
- __ndarray.size__: the number of all elements in the array.
- __ndarray.dtype__: the type of the element in the array, such as numpy.int32, numpy.int16, or numpy.float64.
- __ndarray.itemsize__: the size of each element in the array, in bytes.
- __ndarray.data__: the buffering for storing the array elements. Usually we only need to access the elements by subscripts, and don't need to access the buffer.

Let's take a look at the code example:

In [5]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print('a=')
print(a)
print("a's ndim {}".format(a.ndim))
print("a's shape {}".format(a.shape))
print("a's size {}".format(a.size))
print("a's dtype {}".format(a.dtype))
print("a's itemsize {}".format(a.itemsize))

print('')

print('b=')
print(b)
print("b's ndim {}".format(b.ndim))
print("b's shape {}".format(b.shape))
print("b's size {}".format(b.size))
print("b's dtype {}".format(b.dtype))
print("b's itemsize {}".format(b.itemsize))

a=
[1 2 3]
a's ndim 1
a's shape (3,)
a's size 3
a's dtype int64
a's itemsize 8

b=
[[1 2 3]
 [4 5 6]]
b's ndim 2
b's shape (2, 3)
b's size 6
b's dtype int64
b's itemsize 8


<br>
We can also specify the type of the element when creating the array, for example:

In [6]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

***

## Create a Specific Array

In actual project engineering, we often need some specific data, and some helper functions are provided in NumPy:

- __zeros__: used to create an array whose elements are all 0
- __ones__: used to create an array whose elements are all 1
- __empty__: used to create uninitialized data. so the content is undefined.
- __arange__: used to create an array by specifying the scope and step-length
- __linespace__: used to create an array by specifying the range and the number of elements
- __random__: used to generate random numbers

In [7]:
a = np.zeros((2,3))
print('np.zeros((2,3)= \n{}\n'.format(a))

b = np.ones((2,3))
print('np.ones((2,3))= \n{}\n'.format(b))

c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

d = np.arange(1, 2, 0.3)
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

f = np.random.random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.zeros((2,3)= 
[[0. 0. 0.]
 [0. 0. 0.]]

np.ones((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]

np.empty((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]

np.random.random((2,3))= 
[[0.19420401 0.74963391 0.13520571]
 [0.60284181 0.27032617 0.12150383]]



***

## Shape and Operation

In addition to generating an array, after we have held some data, we may need to generate some new data structures based on the existing array. In this case, we can use the following functions:

- __reshape__: used to generate a new array based on the existing array and the specified shape
- __vstack__: used to stack multiple arrays in vertical direction (the dimensions of the array must be matched)
- __hstack__: used to stack multiple arrays in horizontal direction (the dimensions of the array must be matched)
- __hsplit__: used to split the array horizontally
- __vsplit__: used to split the array vertically

We'll use some examples to illustrate.

### Shapes

To make it easier to test, let's create a few data:

- __zero_line__: an array with a row containing three 0
- __one_column__: an array with a column containing three 1
- __a__: a matrix with 2 rows and 3 columns
- __b__: an integer array in the interval of \[11,20\]

In [8]:
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))
print("zero_line = \n{}\n".format(zero_line))
print("one_column = \n{}\n".format(one_column))

a = np.array([(1,2,3), (4,5,6)])
b = np.arange(11, 20)
print("a = \n{}\n".format(a))
print("b = \n{}\n".format(b))

zero_line = 
[[0. 0. 0.]]

one_column = 
[[1.]
 [1.]
 [1.]]

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



<br>
The array b is a one-dimensional array originally, and we resize it into a matrix of 3 rows and 3 columns by the reshape method:

In [9]:
b = b.reshape(3, -1)
print("b.reshape(3, -1) = \n{}\n".format(b))

b.reshape(3, -1) = 
[[11 12 13]
 [14 15 16]
 [17 18 19]]



The second parameter here is set to -1, which means that it'll be determined based on actual conditions automatically. Since the array has 9 elements originally, the matrix after being resized is 3X3. The code output is as follows:

In [10]:
b.reshape(3, -1)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Stacking

<br>
Next, we'll stack the three arrays vertically through the vstack function:

In [11]:
c = np.vstack((a, b, zero_line))
print("c = np.vstack((a,b, zero_line)) = \n{}\n".format(c))

c = np.vstack((a,b, zero_line)) = 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]



For Vertical Stack - number of coluns should be same.
<br>
For Horizontal Stack - number of rows should be same.

Similarly, we can also use the hstack for horizontal stacking. This time we need to adjust the structure of the array a first:

In [12]:
a = a.reshape(3, 2)
print("a.reshape(3, 2) = \n{}\n".format(a))

d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))

a.reshape(3, 2) = 
[[1 2]
 [3 4]
 [5 6]]

d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]



### Splitting

Next, let's take a look at the split. First, we split the array d into three arrays in horizontal direction. Then we print out the middle one (the subscript is 1):

In [13]:
e = np.hsplit(d, 3) # Split a into 3
print("e = np.hsplit(d, 3) = \n{}\n".format(e))
print("e[1] = \n{}\n".format(e[1]))

e = np.hsplit(d, 3) = 
[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]

e[1] = 
[[11. 12.]
 [14. 15.]
 [17. 18.]]



In addition to specifying number to split the array evenly, we can also specify the number of columns to split. The following is to split the array d from the first column and the third column:

In [14]:
f = np.hsplit(d, (1, 3)) # # Split a after the 1st and the 3rd column
print("f = np.hsplit(d, (1, 3)) = \n{}\n".format(f))

f = np.hsplit(d, (1, 3)) = 
[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]



Finally, we split the array d in the vertical direction. Similarly, if the specified number cannot make the array be split evenly, it will fail:

In [15]:
g = np.vsplit(d, 3)
print("np.hsplit(d, 2) = \n{}\n".format(g))

# np.vsplit(d, 2) # ValueError: array split does not result in an equal division

np.hsplit(d, 2) = 
[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]



***

## Index

Next we look at how to access the data in the NumPy array.
<br><br>
Again, for testing convenience, let's create a one-dimensional array first. Its content is integers in the interval of \[100,200).
<br><br>
Basically, we can specify the subscripts by array\[index\] to access the elements of the array.

In [16]:
base_data = np.arange(100, 200)
print("base_data\n={}\n".format(base_data))

print("base_data[10] = {}\n".format(base_data[10]))

base_data
=[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]

base_data[10] = 110



<br>
In NumPy, we can create an array containing several subscripts to get the elements in the target array. For example:

In [17]:
# Create a numpy array with interval of 5
every_five = np.arange(0, 100, 5)
print("base_data[every_five] = \n{}\n".format(
    base_data[every_five]))

base_data[every_five] = 
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]



<br>
The subscript array can be one-dimensional, or multi-dimensional. Let's suppose that we want to get a 2X2 matrix whose content comes from the four subscripts of 1, 2, 10, and 20 in the target array, so the code can be written:

In [18]:
a = np.array([(1,2), (10,20)])
print("a = \n{}\n".format(a))
print("base_data[a] = \n{}\n".format(base_data[a]))

a = 
[[ 1  2]
 [10 20]]

base_data[a] = 
[[101 102]
 [110 120]]



<br>
The above we see is the case where the target array is one-dimensional. Let's convert the following array into a 10X10 two-dimensional array.

In [19]:
base_data2 = base_data.reshape(10, -1)
print("base_data2 = np.reshape(base_data, (10, -1)) = \n{}\n".format(base_data2))

base_data2 = np.reshape(base_data, (10, -1)) = 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]



<br>

For a two-dimensional array,

- if we only specify one subscript, the result of the access is still an array.
- if we specify two subscripts, the result of the access is the elements inside.
- we can also specify the last element by "-1".

In [20]:
print("base_data2[2] = \n{}\n".format(base_data2[2]))
print("base_data2[2, 3] = \n{}\n".format(base_data2[2, 3]))
print("base_data2[-1, -1] = \n{}\n".format(base_data2[-1, -1]))

base_data2[2] = 
[120 121 122 123 124 125 126 127 128 129]

base_data2[2, 3] = 
123

base_data2[-1, -1] = 
199



<br>

In addition, we can also specify the scope by ":", such as: 2:5 . Only to write ":" indicates the full scope.

Please see the code below:
It will:

- get all the elements of the row whose subscript is 2
- get all the elements of the column whose subscript is 3
- get all the elements of the rows whose subscripts are in \[2,5) and the columns * whose subscripts are in [2,4). Please observe the following output carefully:

In [21]:
print("base_data2[2, :]] = \n{}\n".format(base_data2[2, :]))
print("base_data2[:, 3]] = \n{}\n".format(base_data2[:, 3]))
print("base_data2[2:5, 2:4]] = \n{}\n".format(base_data2[2:5, 2:4]))

base_data2[2, :]] = 
[120 121 122 123 124 125 126 127 128 129]

base_data2[:, 3]] = 
[103 113 123 133 143 153 163 173 183 193]

base_data2[2:5, 2:4]] = 
[[122 123]
 [132 133]
 [142 143]]



***

## Mathematics

There are also a lot of mathematical functions in NumPy. Here are some examples.

In [22]:
base_data = (np.random.random((5, 5)) - 0.5) * 100
print("base_data = \n{}\n".format(base_data))

print("np.amin(base_data) = {}".format(np.amin(base_data)))
print("np.amax(base_data) = {}".format(np.amax(base_data)))
print("np.average(base_data) = {}".format(np.average(base_data)))
print("np.sum(base_data) = {}".format(np.sum(base_data)))
print("np.sin(base_data) = \n{}".format(np.sin(base_data)))

base_data = 
[[ 22.79550129   6.43120664 -26.08145483  24.37572613 -11.76098957]
 [ -8.26257752  19.16868294   2.0147682    1.60098196 -31.01673993]
 [ 21.55507378  -7.99464222  33.56796179   3.63666823  36.07496109]
 [ 27.52485293 -40.01834796  37.30343224  34.49642762 -23.6183453 ]
 [-36.96722736  -8.00645967  -8.89228103 -46.99223902  43.95790287]]

np.amin(base_data) = -46.99223901828161
np.amax(base_data) = 43.95790286535938
np.average(base_data) = 2.5957137316265344
np.sum(base_data) = 64.89284329066336
np.sin(base_data) = 
[[-0.72038185  0.14748139 -0.81266656 -0.68675481  0.72109469]
 [-0.91767961  0.31373777  0.90305275  0.99954445  0.38866903]
 [ 0.42238485 -0.9901236   0.83578305 -0.47509815 -0.99857699]
 [ 0.68125889 -0.73275148 -0.38543537  0.06105358  0.99840992]
 [ 0.66827272 -0.98839773 -0.50768614 -0.13127082 -0.02439187]]


In [23]:
arr = np.arange(1,20)
arr = arr * arr              #Multiplies each element by itself 
print("Multpiles: ",arr)
arr = arr - arr              #Subtracts each element from itself
print("Substracts: ",arr)
arr = np.arange(1,20)
arr = arr + arr              #Adds each element to itself
print("Add: ",arr)
arr = arr / arr              #Divides each element by itself
print("Divide: ",arr)
arr = np.arange(1,20)
arr = arr + 50
print("Add +50: ",arr)

Multpiles:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
Substracts:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Add:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Divide:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Add +50:  [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [24]:
print("Sqrt: ",np.sqrt(arr))   #Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
 7.54983444 7.61577311 7.68114575 7.74596669 7.81024968 7.87400787
 7.93725393 8.         8.06225775 8.1240384  8.18535277 8.24621125
 8.30662386]
Exp:  [1.40934908e+22 3.83100800e+22 1.04137594e+23 2.83075330e+23
 7.69478527e+23 2.09165950e+24 5.68572000e+24 1.54553894e+25
 4.20121040e+25 1.14200739e+26 3.10429794e+26 8.43835667e+26
 2.29378316e+27 6.23514908e+27 1.69488924e+28 4.60718663e+28
 1.25236317e+29 3.40427605e+29 9.25378173e+29]
Sin:  [ 0.67022918  0.98662759  0.39592515 -0.55878905 -0.99975517 -0.521551
  0.43616476  0.99287265  0.63673801 -0.30481062 -0.96611777 -0.7391807
  0.1673557   0.92002604  0.82682868 -0.02655115 -0.85551998 -0.89792768
 -0.11478481]
Cos:  [ 0.7421542  -0.16299078 -0.91828279 -0.82930983  0.02212676  0.85322011
  0.89986683  0.11918014 -0.77108022 -0.95241298 -0.25810164  0.67350716
  0.98589658  0.39185723 -0.56245385 -0.99964746 -0.5177698   0.44014302
  0.99339038]
Log:  [

***

## Matrix

Now, let's take a look at how to use NumPy in a matrix way.

First, let's create a 5X5 random integer matrix. There are two ways to get the transpose of a matrix: __.T__ or transpose function. In addition, the matrix can be multiplied through the __dot function__. The sample code is as follows:

In [25]:
base_data = np.floor((np.random.random((5, 5)) - 0.5) * 100)
print("base_data = \n{}\n".format(base_data))

print("base_data.T = \n{}\n".format(base_data.T))
print("base_data.transpose() = \n{}\n".format(base_data.transpose()))

matrix_one = np.ones((5, 5))
print("matrix_one = \n{}\n".format(matrix_one))

minus_one = np.dot(matrix_one, -1)
print("minus_one = \n{}\n".format(minus_one))

print("np.dot(base_data, minus_one) = \n{}\n".format(
    np.dot(base_data, minus_one)))

base_data = 
[[ -9.  47.   6. -24.  10.]
 [-48. -37.   1. -47.  49.]
 [ 26.  -5.  12.  46.  43.]
 [-16.  -5.  24. -42. -31.]
 [  4.  -5.  32. -39.  33.]]

base_data.T = 
[[ -9. -48.  26. -16.   4.]
 [ 47. -37.  -5.  -5.  -5.]
 [  6.   1.  12.  24.  32.]
 [-24. -47.  46. -42. -39.]
 [ 10.  49.  43. -31.  33.]]

base_data.transpose() = 
[[ -9. -48.  26. -16.   4.]
 [ 47. -37.  -5.  -5.  -5.]
 [  6.   1.  12.  24.  32.]
 [-24. -47.  46. -42. -39.]
 [ 10.  49.  43. -31.  33.]]

matrix_one = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

minus_one = 
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

np.dot(base_data, minus_one) = 
[[ -30.  -30.  -30.  -30.  -30.]
 [  82.   82.   82.   82.   82.]
 [-122. -122. -122. -122. -122.]
 [  70.   70.   70.   70.   70.]
 [ -25.  -25.  -25.  -25.  -25.]]



***

## Random Numbers

At the end of the article, let's take a look at the use of random numbers.

Random numbers are a feature we use very often during the programming process, such as generating demo data, or disordering existing data sequence randomly to segment the modeling data and the verification data.

The __numpy.random__ package contains a number of algorithms for random numbers. Here we list the four most common usage:

The four usages are:

- to generate 20 random numbers, each of which is between __\[0.0, 1.0)__
- to generate a random number based on the __specified shape__
- to generate a specified number (such as 20) of random integers within the __specified range (such as [0, 100))__
- to disorder the sequence of the __existing data ([0, 1, 2, ..., 19])__ randomly The output is as follows:

In [26]:
print("random: {}\n".format(np.random.random(20)));

print("rand: {}\n".format(np.random.rand(3, 4)));

print("randint: {}\n".format(np.random.randint(0, 100, 20)));

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));

random: [0.63754    0.96667946 0.18108227 0.36117424 0.26143141 0.01423574
 0.63377366 0.54979736 0.75989222 0.76344805 0.07761519 0.65737486
 0.81196337 0.89524545 0.28521593 0.8965784  0.16129443 0.71979614
 0.93170312 0.33618515]

rand: [[0.93712038 0.19733771 0.36629357 0.94614191]
 [0.66480417 0.58844339 0.8081541  0.4923562 ]
 [0.76468709 0.46924445 0.71601159 0.26544815]]

randint: [15 31 87 85 62 75 21 50 96 96 62 50 32 89 20 60 92 34 63 82]

permutation: [16 12  2 18 11 13  7  4  8 17  0 14  1 10 15  5  3 19  9  6]



***

## References

- https://www.tutorialdocs.com/article/python-numpy-tutorial.html
- https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f
- http://www.numpy.org
- https://www.kaggle.com/abdullahsahin/numpy-tutorial-for-beginner